version: "3.8"

services:
  backend:
    build:
      context: ./src/server
    image: polling-app:latest
    ports:
      - "5001:5000"
    depends_on:
      - mongo
    volumes:
      - ./src/server:/app
    environment:
      - PYTHONUNBUFFERED=1

  mongo:
    build:
      context: ./mongo
    image: mongo-polling:latest
    ports:
      - "27017:27017"
    restart: always

  frontend:
    build:
      context: ./src
    image: polling-frontend:latest
    ports:
      - "3000:3000"
    restart: always
    environment:
      - NODE_ENV=production
