version: "3.8"

services:
  backend:
    build:
      context: ./src/server
    ports:
      - "5001:5000"
    depends_on:
      - mongo
    volumes:
      - ./src/server:/app
    environment:
      - PYTHONUNBUFFERED=1

  mongo:
    image: 686728032722.dkr.ecr.us-west-2.amazonaws.com/mongo-polling:latest
    ports:
      - "27017:27017"
    restart: always
